export const BEAMMP_ROUTE_NAME = "menu.beammp"
export const BEAMMP_TOS_ROUTE_NAME = "menu.beammp.tos"
export const BEAMMP_LAUNCHER_ROUTE_NAME = "menu.beammp.launcher"
export const BEAMMP_LOGIN_ROUTE_NAME = "menu.beammp.login"
export const BEAMMP_TILES_ROUTE_NAME = "menu.beammp.tiles"
export const BEAMMP_SERVERS_ROUTE_NAME = "menu.beammp.servers"
export const BEAMMP_CURRENT_SERVER_ROUTE_NAME = "menu.beammp.current-server"
export const BEAMMP_DIRECT_ROUTE_NAME = "menu.beammp.direct"
